In [1]:
!pip install torch transformers

In [2]:
import torch #for core openrations, like tensors, numbers
import torch.nn as nn # to build neural networks
from transformers import AutoModelForCausalLM, AutoTokenizer # AutoModelForCasualLm - helps us load a pretrained language model, #AutoTokenizer - convert text to numbers (tensors)

In [3]:
model = nn.Linear(in_features=2,out_features=1) # y = w1*x1 + w2*x2+b1
# weights = [w1,w2]
#bias = [b1]

In [4]:
for name, param in model.named_parameters():
  print(f"{name}")
  print(param.data)
  print("Shape : ",param.shape)
  print("\n")

weight
tensor([[0.3546, 0.6098]])
Shape :  torch.Size([1, 2])


bias
tensor([-0.4662])
Shape :  torch.Size([1])




In [5]:
a = model.parameters()
print(a)

<generator object Module.parameters at 0x78729ca9e420>


In [6]:
for param in model.parameters():
  print(param)

Parameter containing:
tensor([[0.3546, 0.6098]], requires_grad=True)
Parameter containing:
tensor([-0.4662], requires_grad=True)


In [7]:
total_params = sum(param.numel() for param in model.parameters())
print(total_params)

3


In [8]:
#input
x = torch.tensor([[1.0, 2.0]])

output = model(x)

print("Input : ", x)
print("output : ",output)

Input :  tensor([[1., 2.]])
output :  tensor([[1.1081]], grad_fn=<AddmmBackward0>)


In [ ]:
# internally : y = -0.3713*1.0 + -0.6214*2.0 + 0.6161

In [9]:
y = -0.3713*1.0 + -0.6214*2.0 + 0.6161
print(y)

-0.9979999999999999


In [ ]:
# y = ((weight matrix)^Transpose) * Input matrix + bias matrix

In [10]:
inp = torch.tensor([
    [1.0,2.0,7.0],
    [3.0,4.0,8.0],
    [5.0,5.0,9.0]
])



out = model(inp)
print(out)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x3 and 2x1)

In [11]:
inp = torch.tensor([
    [1.0,2.0],
    [3.0,4.0],
    [5.0,5.0]
])



out = model(inp)
print(out)

tensor([[1.1081],
        [3.0371],
        [4.3562]], grad_fn=<AddmmBackward0>)


In [12]:
model_name = "distilgpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
hf_model = AutoModelForCausalLM.from_pretrained(model_name)


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: distilgpt2
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
transformer.h.{0, 1, 2, 3, 4, 5}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [13]:
for name, param in hf_model.named_parameters():
  print(f"{name}")
  print(param.data)
  print("Shape : ",param.shape)
  print("\n")

Streaming output truncated to the last 5000 lines.
        1.2633, 1.2558, 0.0973, 1.1412, 1.1556, 0.9241, 0.1714, 1.1207, 1.2885,
        1.0745, 1.2164, 0.1518, 0.6955, 1.3562, 1.0547, 1.2070, 1.3063, 0.1745,
        1.2013, 1.2218, 1.0861, 1.2356, 1.3082, 1.2611, 1.0634, 1.1215, 1.0115,
        1.0830, 0.7319, 0.9046, 1.1562, 1.1749, 0.1237, 1.1395, 1.1310, 0.1996,
        1.1593, 1.1196, 1.2044, 0.2194, 0.7276, 1.1729, 1.0462, 0.3003, 1.3959,
        1.1045, 0.1359, 0.4823, 0.1530, 1.2100, 1.2328, 0.3153, 1.1678, 1.2607,
        1.0601, 1.2619, 0.9988, 1.0847, 1.1790, 0.1125, 1.1524, 1.2021, 1.2061,
        1.1699, 0.1358, 0.8962, 0.0722, 0.1975, 0.1239, 1.0668, 1.0553, 0.1493,
        0.7806, 0.1210, 1.2191, 0.1492, 1.0404, 0.2046, 1.1512, 0.2542, 1.3172,
        0.2869, 1.3738, 0.1229, 1.1361, 1.0479, 1.1613, 1.1582, 1.1742, 0.3119,
        1.1827, 0.2887, 1.1185, 0.9024, 0.2013, 1.1963, 1.1251, 1.2221, 0.2529,
        1.2811, 1.2094, 1.2055, 0.8493, 0.0806, 0.9366, 1.1807, 1.106

In [14]:
total_params = sum(param.numel() for param in hf_model.parameters())
print(total_params)

81912576


In [15]:
total_params_ref = sum(param.numel() for param in hf_model.parameters())
print(f"total parameters in {model} : {total_params_ref/1e6:.2f} Million")

total parameters in Linear(in_features=2, out_features=1, bias=True) : 81.91 Million


In [16]:
print(hf_model)

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-5): 6 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)


In [17]:
layer = hf_model.transformer.h[0]
print(layer)

GPT2Block(
  (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  (attn): GPT2Attention(
    (c_attn): Conv1D(nf=2304, nx=768)
    (c_proj): Conv1D(nf=768, nx=768)
    (attn_dropout): Dropout(p=0.1, inplace=False)
    (resid_dropout): Dropout(p=0.1, inplace=False)
  )
  (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  (mlp): GPT2MLP(
    (c_fc): Conv1D(nf=3072, nx=768)
    (c_proj): Conv1D(nf=768, nx=3072)
    (act): NewGELUActivation()
    (dropout): Dropout(p=0.1, inplace=False)
  )
)


In [20]:
weights = layer.attn.c_attn.weight
print("Shape", weights.shape)
print(weights)

Shape torch.Size([768, 2304])
Parameter containing:
tensor([[-0.4988, -0.1990, -0.1046,  ...,  0.0169, -0.0458,  0.0232],
        [ 0.0116,  0.1446,  0.2648,  ..., -0.0512, -0.0114,  0.0102],
        [-0.0121,  0.1221,  0.4106,  ...,  0.0788,  0.0287,  0.0026],
        ...,
        [-0.2501, -0.0507,  0.1911,  ...,  0.0488, -0.0518,  0.0534],
        [ 0.1663,  0.2111,  0.0661,  ...,  0.0751, -0.0039, -0.0271],
        [-0.4030, -0.1348, -0.2251,  ..., -0.0164,  0.0234,  0.0375]],
       requires_grad=True)


In [21]:
weights = layer.attn.c_attn.weight
print("Shape", weights.shape)
print(weights[:5,:5])

Shape torch.Size([768, 2304])
tensor([[-0.4988, -0.1990, -0.1046, -0.3371,  0.2440],
        [ 0.0116,  0.1446,  0.2648,  0.2857,  0.6108],
        [-0.0121,  0.1221,  0.4106, -0.0278, -0.1448],
        [ 0.2076, -0.2812,  0.0111,  0.4729,  0.3349],
        [-0.0259,  0.1266,  0.0089,  0.5926,  0.3209]],
       grad_fn=<SliceBackward0>)


In [25]:
input_text = "AI will change the world because"
inputs = tokenizer(input_text, return_tensors = "pt")

outputs = hf_model.generate(**inputs,max_length = 30)

print(tokenizer.decode(outputs[0]))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


AI will change the world because of the fact that the world is not a place where people are allowed to live.









In [26]:
input_text = "Humans will rule AI becuase"
inputs = tokenizer(input_text, return_tensors = "pt")

outputs = hf_model.generate(**inputs,max_length = 30)

print(tokenizer.decode(outputs[0]))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


Humans will rule AI becuase they will be able to control the AI.













